#!/bin/bash

# A "|" separated list of files to exclude from symoblic linking
exclude="dot|README.md"
files=$(ls | egrep -v "\b($exclude)\b")

install() {
    for file in $files; do
        ln -vfs $(pwd)/$file ~/.$file
    done
}

remove() {
    for file in $files; do
        rm -vf ~/.$file
    done
}

case $1 in
    "install" )
        remove
        install
        ;;
    "remove" )
        remove
        ;;
    * )
        echo "$0 install remove"
        ;;
esac
