#!/bin/bash

VPM_HOME=~/dotfiles

install() {
    name=$(basename $1 | sed 's/\.git//')
    git submodule add --name $name $1 vim/bundle/$name
    git commit -em "Installed $name"
}

remove() {
    git submodule deinit $1
    git rm $1
    git add .gitmodules
    git commit -em "Removed $(basename $1)"
}

update() {
    git submodule foreach git pull origin master
    git commit -eam "Updated Vim Plugins"
}

cd $VPM_HOME
case $1 in
    "install" )
        install $2
        ;;
    "remove" )
        remove $2
        ;;
    "update" )
        update
        ;;
    * )
        prog=$(basename $0)
        echo "Usage:"
        echo "$prog install <git URI>"
        echo "$prog remove  <submodule directory>"
        echo "$prog update"
        ;;
esac
